### PR TITLE
Add support for netstandard20

### PR DESCRIPTION
**Pull request by gdziadkiewicz**
This changes the target framework from netstandard21 to netstandard20 and adds test execution on net481.

### CODE REVIEW

**Comment by gdziadkiewicz** [comment]
@misterspeedy could you take a look at this small one? This is for the netstandard21 -> netstandard20 change and extension of tests.

@smoothdeveloper could you also take a look and review if this plays well with your needs?

**Comment by smoothdeveloper** [comment]
@gdziadkiewicz could you also adjust .\FsExcel\src\Scripts\CreateRegressionTestActuals.fsx to load from netstandard2.0 location?

After doing this, I was able to run the script under fsianycpu.exe on windows from your branch, which is what I was looking after.

**Comment by gdziadkiewicz** [comment]
Done

**Comment by smoothdeveloper** [comment]
Thanks!

**Comment by misterspeedy** [comment]
Merged!  Thanks guys!

**Pull request merged**
